cargo run -r --package icfpc2023 --bin chokudai < problems/problem-1.json > out/1.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-2.json > out/2.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-3.json > out/3.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-4.json > out/4.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-5.json > out/5.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-6.json > out/6.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-7.json > out/7.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-8.json > out/8.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-9.json > out/9.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-10.json > out/10.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-11.json > out/11.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-12.json > out/12.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-13.json > out/13.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-14.json > out/14.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-15.json > out/15.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-16.json > out/16.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-17.json > out/17.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-18.json > out/18.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-19.json > out/19.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-20.json > out/20.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-21.json > out/21.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-22.json > out/22.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-23.json > out/23.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-24.json > out/24.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-25.json > out/25.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-26.json > out/26.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-27.json > out/27.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-28.json > out/28.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-29.json > out/29.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-30.json > out/30.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-31.json > out/31.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-32.json > out/32.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-33.json > out/33.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-34.json > out/34.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-35.json > out/35.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-36.json > out/36.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-37.json > out/37.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-38.json > out/38.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-39.json > out/39.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-40.json > out/40.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-41.json > out/41.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-42.json > out/42.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-43.json > out/43.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-44.json > out/44.json
cargo run -r --package icfpc2023 --bin chokudai < problems/problem-45.json > out/45.json
