[package]
name = "vis"
version = "0.1.0"
authors = ["Yoichi Iwata"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.73"
js-sys = "0.3.56"
svg = "0.13.1"
icfpc2023 = { path = "../", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.2"
